rocketmq:
  name-server: 123.207.202.228:9876
  producer:
    group: iot-group
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 2
    retry-times-when-send-failed: 2
    max-message-size: 4096
    compress-message-body-threshold: 4096
    retry-next-server: false
