rocketmq:
  name-server: ENC(Xyw2NH4Z8b3ePg7z3tyfDshlENBmLapBbOuMWGGeBSxU8tU1nOSBdBcW8DNC245W4vOsF2Al4E2kwBFlVcfF+w==)
  producer:
    group: ENC(y/Rng3fG65OT4T9L6+T2UB5M1sVR+juYucIn5H9pqMH/dyMtamZeo0e+u+VrBimi)
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 2
    retry-times-when-send-failed: 2
    max-message-size: 4096
    compress-message-body-threshold: 4096
    retry-next-server: false
spring:
  data:
    redis:
      database: 0
      port: 6379
      host: ENC(ie8hf2W1RPMjzigdJK1MnhtQF3rmkDJGMgS6XvRFqOVkSuADmKLXkhO9xomPrDRA)
      password: ENC(kDrmhVebkri4qOWkNYV6qTAfceC5u7YoDANKOfspQKnghZjKOQZceqW6y+CSvJ/T70NENbiWdV0h+RZrFYZq+g==)
      timeout: 1000
      connect-timeout: 10000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 6f644ce5-f1c6-4157-8d48-d6c4306280a8