spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  data:
    redis:
      database: 0
      port: 6379
      host: 127.0.0.1
      password:
      timeout: 1000
      connect-timeout: 10000
