server:
  port: 9090
spring:
  application:
    name: iotp-web
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true
  freemarker:
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
