spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ENC(G53QMXt+21B5wnqtJve6ds2QiMi4LwuqFxaGaO27Fy/8lDTkkc5xx9YMGyAXAR+rpQNEs7aNpRvOBs6DvW4vfxUA/rrPa+GCGRGm/d+WnNoJkLdPfHZ6fjxGoNWen2zWxOKsLJ8kEK/pXsZy0iHGQw==)?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(K3C5Ec5sD0+ZnZcuDxeLopaJD5UqD+jKaQLUzbHpPFV94LDpRcmaC/GPwXbRQqeD/s609M1sI96iLTiwzBTWgA==)
    password: ENC(fVNQYvnHHl14FKevHvfkyRS4GlU824oRTrIXZ9yfb6Z56tESyJGCmb6ITHWAloD8JszvDoDe3Ol0dTdxerAyqw==)
  data:
    redis:
      database: 0
      port: 6379
      host: ENC(ie8hf2W1RPMjzigdJK1MnhtQF3rmkDJGMgS6XvRFqOVkSuADmKLXkhO9xomPrDRA)
      password: ENC(kDrmhVebkri4qOWkNYV6qTAfceC5u7YoDANKOfspQKnghZjKOQZceqW6y+CSvJ/T70NENbiWdV0h+RZrFYZq+g==)
      timeout: 1000
      connect-timeout: 10000
